USE inventory_management_db;

-- ============================================================
-- SEED DATA
-- ============================================================

-- ------------------------------------------------------------
-- 1. CATEGORIES
-- ------------------------------------------------------------

INSERT INTO categories (category_name, status) VALUES
('General', 1),
('Electronics', 1),
('Office Supplies', 1),
('Computer Accessories', 1),
('Cleaning Supplies', 1),
('Pantry', 1)
ON DUPLICATE KEY UPDATE
    status = VALUES(status);


-- ------------------------------------------------------------
-- 2. SUPPLIERS
-- ------------------------------------------------------------

INSERT INTO suppliers
(supplier_name, contact_person, phone, address, status)
VALUES
(
    'Cebu Office Solutions',
    'Juan Dela Cruz',
    '09171234567',
    'Cebu City, Cebu, Philippines',
    1
),
(
    'TechSource Philippines',
    'Maria Santos',
    '09181234567',
    'Mandaue City, Cebu, Philippines',
    1
),
(
    'Visayas General Trading',
    'Pedro Garcia',
    '09191234567',
    'Lapu-Lapu City, Cebu, Philippines',
    1
),
(
    'Prime Cleaning Supplies',
    'Ana Reyes',
    '09201234567',
    'Cebu City, Cebu, Philippines',
    1
),
(
    'Pacific Pantry Supply',
    'Carlos Ramos',
    '09211234567',
    'Mandaue City, Cebu, Philippines',
    1
)
ON DUPLICATE KEY UPDATE
    contact_person = VALUES(contact_person),
    phone = VALUES(phone),
    address = VALUES(address),
    status = VALUES(status);


-- ------------------------------------------------------------
-- 3. USERS
-- ------------------------------------------------------------
-- IMPORTANT:
-- These are example bcrypt hashes.
-- Replace them with hashes generated by your application's
-- password hashing system.
--
-- Example accounts:
-- admin / password
-- staff  / password
--
-- DO NOT use these passwords in production.

INSERT INTO users
(first_name, middle_name, last_name, username, password, role_id, status)
SELECT
    'System',
    NULL,
    'Administrator',
    'admin',
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC4J2d4K5L7X1Q7X7K',
    id,
    1
FROM roles
WHERE role_name = 'admin'
ON DUPLICATE KEY UPDATE
    first_name = VALUES(first_name),
    last_name = VALUES(last_name),
    role_id = VALUES(role_id),
    status = VALUES(status);


INSERT INTO users
(first_name, middle_name, last_name, username, password, role_id, status)
SELECT
    'Inventory',
    NULL,
    'Staff',
    'staff',
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC4J2d4K5L7X1Q7X7K',
    id,
    1
FROM roles
WHERE role_name = 'staff'
ON DUPLICATE KEY UPDATE
    first_name = VALUES(first_name),
    last_name = VALUES(last_name),
    role_id = VALUES(role_id),
    status = VALUES(status);


-- ------------------------------------------------------------
-- 4. PRODUCTS
-- ------------------------------------------------------------

INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'GEN-001',
    'Ballpen - Blue',
    'piece',
    5.00,
    8.00,
    150,
    30,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Office Supplies'
  AND s.supplier_name = 'Cebu Office Solutions'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'GEN-002',
    'Notebook - A5',
    'piece',
    35.00,
    50.00,
    80,
    20,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Office Supplies'
  AND s.supplier_name = 'Cebu Office Solutions'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'ELEC-001',
    'USB Keyboard',
    'piece',
    450.00,
    650.00,
    25,
    5,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Electronics'
  AND s.supplier_name = 'TechSource Philippines'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'ELEC-002',
    'Wireless Mouse',
    'piece',
    350.00,
    550.00,
    30,
    8,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Computer Accessories'
  AND s.supplier_name = 'TechSource Philippines'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'ELEC-003',
    'HDMI Cable 2m',
    'piece',
    120.00,
    200.00,
    18,
    5,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Computer Accessories'
  AND s.supplier_name = 'TechSource Philippines'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'OFF-001',
    'Bond Paper A4',
    'ream',
    180.00,
    230.00,
    45,
    10,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Office Supplies'
  AND s.supplier_name = 'Cebu Office Solutions'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'OFF-002',
    'Stapler - Standard',
    'piece',
    85.00,
    120.00,
    20,
    5,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Office Supplies'
  AND s.supplier_name = 'Cebu Office Solutions'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'CLN-001',
    'Multi-Purpose Cleaner',
    'bottle',
    95.00,
    130.00,
    35,
    10,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Cleaning Supplies'
  AND s.supplier_name = 'Prime Cleaning Supplies'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'CLN-002',
    'Tissue Paper',
    'pack',
    45.00,
    65.00,
    60,
    15,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Cleaning Supplies'
  AND s.supplier_name = 'Prime Cleaning Supplies'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'PAN-001',
    'Bottled Water 500ml',
    'bottle',
    12.00,
    18.00,
    100,
    25,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Pantry'
  AND s.supplier_name = 'Pacific Pantry Supply'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


INSERT INTO products
(
    category_id,
    supplier_id,
    product_code,
    product_name,
    unit,
    cost_price,
    selling_price,
    stock,
    reorder_level,
    status
)
SELECT
    c.id,
    s.id,
    'PAN-002',
    'Coffee 3-in-1',
    'box',
    95.00,
    125.00,
    40,
    10,
    1
FROM categories c
JOIN suppliers s
WHERE c.category_name = 'Pantry'
  AND s.supplier_name = 'Pacific Pantry Supply'
ON DUPLICATE KEY UPDATE
    product_name = VALUES(product_name),
    category_id = VALUES(category_id),
    supplier_id = VALUES(supplier_id),
    unit = VALUES(unit),
    cost_price = VALUES(cost_price),
    selling_price = VALUES(selling_price),
    stock = VALUES(stock),
    reorder_level = VALUES(reorder_level),
    status = VALUES(status);


-- ------------------------------------------------------------
-- 5. STOCK-IN TRANSACTIONS
-- ------------------------------------------------------------

INSERT INTO stock_transactions
(
    transaction_no,
    type,
    supplier_id,
    remarks,
    created_by
)
SELECT
    'SIN-2026-0001',
    'stock_in',
    s.id,
    'Initial inventory stock-in',
    u.id
FROM suppliers s
JOIN users u
WHERE s.supplier_name = 'Cebu Office Solutions'
  AND u.username = 'admin'
ON DUPLICATE KEY UPDATE
    remarks = VALUES(remarks);


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    150,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SIN-2026-0001'
  AND p.product_code = 'GEN-001'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    80,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SIN-2026-0001'
  AND p.product_code = 'GEN-002'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


INSERT INTO stock_transactions
(
    transaction_no,
    type,
    supplier_id,
    remarks,
    created_by
)
SELECT
    'SIN-2026-0002',
    'stock_in',
    s.id,
    'Electronics inventory delivery',
    u.id
FROM suppliers s
JOIN users u
WHERE s.supplier_name = 'TechSource Philippines'
  AND u.username = 'admin'
ON DUPLICATE KEY UPDATE
    remarks = VALUES(remarks);


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    25,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SIN-2026-0002'
  AND p.product_code = 'ELEC-001'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    30,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SIN-2026-0002'
  AND p.product_code = 'ELEC-002'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


-- ------------------------------------------------------------
-- 6. STOCK-OUT TRANSACTION
-- ------------------------------------------------------------

INSERT INTO stock_transactions
(
    transaction_no,
    type,
    supplier_id,
    remarks,
    created_by
)
SELECT
    'SOUT-2026-0001',
    'stock_out',
    NULL,
    'Issued office supplies for daily operations',
    u.id
FROM users u
WHERE u.username = 'staff'
ON DUPLICATE KEY UPDATE
    remarks = VALUES(remarks);


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    10,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SOUT-2026-0001'
  AND p.product_code = 'GEN-001'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


INSERT INTO stock_transaction_items
(
    transaction_id,
    product_id,
    quantity,
    cost_price
)
SELECT
    t.id,
    p.id,
    5,
    p.cost_price
FROM stock_transactions t
JOIN products p
WHERE t.transaction_no = 'SOUT-2026-0001'
  AND p.product_code = 'GEN-002'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_transaction_items sti
      WHERE sti.transaction_id = t.id
        AND sti.product_id = p.id
  );


-- ------------------------------------------------------------
-- 7. STOCK ADJUSTMENT
-- ------------------------------------------------------------

INSERT INTO stock_adjustments
(
    product_id,
    system_stock,
    actual_stock,
    difference,
    reason,
    created_by
)
SELECT
    p.id,
    18,
    17,
    -1,
    'Damaged item discovered during physical inventory',
    u.id
FROM products p
JOIN users u
WHERE p.product_code = 'ELEC-003'
  AND u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM stock_adjustments sa
      WHERE sa.product_id = p.id
        AND sa.reason = 'Damaged item discovered during physical inventory'
  );


-- ------------------------------------------------------------
-- 8. ACTIVITY LOGS
-- ------------------------------------------------------------

INSERT INTO activity_logs
(
    user_id,
    action,
    description,
    ip_address
)
SELECT
    u.id,
    'LOGIN',
    'Administrator logged into the inventory management system.',
    '127.0.0.1'
FROM users u
WHERE u.username = 'admin';


INSERT INTO activity_logs
(
    user_id,
    action,
    description,
    ip_address
)
SELECT
    u.id,
    'PRODUCT_CREATED',
    'Initial product master data was created.',
    '127.0.0.1'
FROM users u
WHERE u.username = 'admin';


INSERT INTO activity_logs
(
    user_id,
    action,
    description,
    ip_address
)
SELECT
    u.id,
    'STOCK_IN',
    'Initial inventory stock-in transaction was recorded.',
    '127.0.0.1'
FROM users u
WHERE u.username = 'admin';


INSERT INTO activity_logs
(
    user_id,
    action,
    description,
    ip_address
)
SELECT
    u.id,
    'STOCK_OUT',
    'Office supplies were issued for daily operations.',
    '127.0.0.1'
FROM users u
WHERE u.username = 'staff';


-- ============================================================
-- OPTIONAL VERIFICATION QUERIES
-- ============================================================

SELECT
    r.id,
    r.role_name,
    COUNT(rp.id) AS permission_count
FROM roles r
LEFT JOIN role_permissions rp
    ON rp.role_id = r.id
GROUP BY r.id, r.role_name
ORDER BY r.id;


SELECT
    p.product_code,
    p.product_name,
    c.category_name,
    s.supplier_name,
    p.stock,
    p.reorder_level,
    p.cost_price,
    p.selling_price
FROM products p
JOIN categories c
    ON c.id = p.category_id
LEFT JOIN suppliers s
    ON s.id = p.supplier_id
ORDER BY p.id;


SELECT
    st.transaction_no,
    st.type,
    COUNT(sti.id) AS item_count,
    u.username AS created_by,
    st.created_at
FROM stock_transactions st
JOIN users u
    ON u.id = st.created_by
LEFT JOIN stock_transaction_items sti
    ON sti.transaction_id = st.id
GROUP BY
    st.id,
    st.transaction_no,
    st.type,
    u.username,
    st.created_at
ORDER BY st.id;
